### ISSUE TITLE
Static method and $this

### ISSUE THREAD

**Issue by ttimot24** [JackieDo/Laravel-Log-Reader#23]
Hi!

In the documentation you mention that methods can be called statically like this:
 $entries = LogReader::filename($file)->get();

But I  get this exception for every method, even count() too:
Non-static method Jackiedo\LogReader\LogReader::filename() should not be called statically, assuming $this from incompatible context

I can't use dependency injection, because I use a dynamic routing that not allows it.
What should I do?

Thanks!
Tim

**Comment by JackieDo** [comment]
Hi @ttimot24 !

If you don't want to use dependency injection, you can use the `Jackiedo\LogReader\Facades\LogReader` facade. Don't use the `Jackiedo\LogReader\LogReader` class directly, because it have not any static method. Please use the facade instead, it will transform the methods themselves into static:

```php
<?php

use Jackiedo\LogReader\Facades\LogReader;
...
...
$entries = LogReader::filename($file)->get();

```

**Comment by ttimot24** [comment]
Thanks! It works!
